import { IMatch } from '../types'

export const february: IMatch[] = [
    {
        date: '01.02',
        time: '02:00',
        first: 'Elche',
        second: 'Barcelona',
        tournament: 'LaLiga',
    },
    {
        date: '01.02',
        time: '02:00',
        first: 'Liverpool',
        second: 'NewcastleUnited',
        tournament: 'EPL',
    },
    {
        date: '01.02',
        time: '02:05',
        first: 'Monaco',
        second: 'Renn',
        tournament: 'Ligue 1',
    },
    {
        date: '01.02',
        time: '19:00',
        first: 'RealMadrid',
        second: 'RayoVallecano',
        tournament: 'LaLiga',
    },
    {
        date: '01.02',
        time: '20:00',
        first: 'AstonVilla',
        second: 'Brentford',
        tournament: 'EPL',
    },
    {
        date: '01.02',
        time: '20:00',
        first: 'ManchesterUnited',
        second: 'Fulham',
        tournament: 'EPL',
    },
    {
        date: '01.02',
        time: '20:00',
        first: 'NottinghamForest',
        second: 'CrystalPalace',
        tournament: 'EPL',
    },
    {
        date: '01.02',
        time: '20:00',
        first: 'Como',
        second: 'Atalanta',
        tournament: 'Seria A',
    },
    {
        date: '01.02',
        time: '20:00',
        first: 'Lyon',
        second: 'Lille',
        tournament: 'Ligue 1',
    },
    {
        date: '01.02',
        time: '22:30',
        first: 'Tottenham',
        second: 'ManchesterCity',
        tournament: 'EPL',
    },
    {
        date: '01.02',
        time: '22:30',
        first: 'BorussiaDortmund',
        second: 'Heidenheim',
        tournament: 'Bundesliga',
    },
    {
        date: '01.02',
        time: '23:00',
        first: 'Cremonese',
        second: 'Inter',
        tournament: 'Seria A',
    },
    {
        date: '02.02',
        time: '01:45',
        first: 'Parma',
        second: 'Juventus',
        tournament: 'Seria A',
    },
    {
        date: '02.02',
        time: '01:45',
        first: 'Strasbourg',
        second: 'PSG',
        tournament: 'Ligue 1',
    },
    {
        date: '03.02',
        time: '01:45',
        first: 'Udinese',
        second: 'Roma',
        tournament: 'Seria A',
    },
    {
        date: '04.02',
        time: '01:45',
        first: 'Bologna',
        second: 'Milan',
        tournament: 'Seria A',
    },
    // {
    //     date: '',
    //     time: '',
    //     first: ,
    //     second: ,
    //     tournament: ,
    // },
    // {
    //     date: '',
    //     time: '',
    //     first: ,
    //     second: ,
    //     tournament: ,
    // },
    // {
    //     date: '',
    //     time: '',
    //     first: ,
    //     second: ,
    //     tournament: ,
    // },
]
