import { IMatch } from '../types'

export const january: IMatch[] = [
    {
        date: '29.01',
        time: '02:00',
        first: 'AtleticBilbao',
        second: 'Sporting',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'Liverpool',
        second: 'Qarabag',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'Barcelona',
        second: 'Copenhagen',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'Monaco',
        second: 'Juventus',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'Ajax',
        second: 'Olympiacos',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'PSG',
        second: 'NewcastleUnited',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'BorussiaDortmund',
        second: 'Inter',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'Napoli',
        second: 'Chelsea',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'Eintracht',
        second: 'Tottenham',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'AtleticoMadrid',
        second: 'BodoGlimt',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'Bayer',
        second: 'Villereal',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'Arsenal',
        second: 'Kairat',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'ManchesterCity',
        second: 'Galatasaray',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'Brugge',
        second: 'Marsel',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'Benfica',
        second: 'RealMadrid',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'PSV',
        second: 'BayernMunchen',
        tournament: 'UCL',
    },
]
