import { IMatch } from '../types'

export const january: IMatch[] = [
    {
        date: '29.01',
        time: '02:00',
        first: 'AtleticBilbao',
        second: 'Sporting',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'Liverpool',
        second: 'Qarabag',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'Barcelona',
        second: 'Copenhagen',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'Monaco',
        second: 'Juventus',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'Ajax',
        second: 'Olympiacos',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'PSG',
        second: 'NewcastleUnited',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'BorussiaDortmund',
        second: 'Inter',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'Napoli',
        second: 'Chelsea',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'Eintracht',
        second: 'Tottenham',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'AtleticoMadrid',
        second: 'BodoGlimt',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'Bayer',
        second: 'Villereal',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'Arsenal',
        second: 'Kairat',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'ManchesterCity',
        second: 'Galatasaray',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'Brugge',
        second: 'Marsel',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'Benfica',
        second: 'RealMadrid',
        tournament: 'UCL',
    },
    {
        date: '29.01',
        time: '02:00',
        first: 'PSV',
        second: 'BayernMunchen',
        tournament: 'UCL',
    },
    {
        date: '31.01',
        time: '01:45',
        first: 'Lens',
        second: 'Havre',
        tournament: 'Ligue 1',
    },
    {
        date: '31.01',
        time: '20:30',
        first: 'Eintracht',
        second: 'Bayer',
        tournament: 'Bundesliga',
    },
    {
        date: '31.01',
        time: '21:00',
        first: 'LeedsUnited',
        second: 'Arsenal',
        tournament: 'EPL',
    },
    {
        date: '31.01',
        time: '21:00',
        first: 'Brighton',
        second: 'Everton',
        tournament: 'EPL',
    },
    {
        date: '31.01',
        time: '22:00',
        first: 'Paris',
        second: 'Marsel',
        tournament: 'Ligue 1',
    },
    {
        date: '31.01',
        time: '23:00',
        first: 'Napoli',
        second: 'Fiorentina',
        tournament: 'Seria A',
    },
    {
        date: '31.01',
        time: '23:30',
        first: 'Chelsea',
        second: 'WestHamUnited',
        tournament: 'EPL',
    },
    {
        date: '31.01',
        time: '23:30',
        first: 'Levante',
        second: 'AtleticoMadrid',
        tournament: 'LaLiga',
    },
    {
        date: '31.01',
        time: '23:30',
        first: 'Hamburger',
        second: 'BayernMunchen',
        tournament: 'Bundesliga',
    },
    {
        date: '01.02',
        time: '02:00',
        first: 'Elche',
        second: 'Barcelona',
        tournament: 'LaLiga',
    },
    {
        date: '01.02',
        time: '02:00',
        first: 'Liverpool',
        second: 'NewcastleUnited',
        tournament: 'EPL',
    },
    {
        date: '01.02',
        time: '02:05',
        first: 'Monaco',
        second: 'Renn',
        tournament: 'Ligue 1',
    },
    {
        date: '01.02',
        time: '19:00',
        first: 'RealMadrid',
        second: 'RayoVallecano',
        tournament: 'LaLiga',
    },
    {
        date: '01.02',
        time: '20:00',
        first: 'AstonVilla',
        second: 'Brentford',
        tournament: 'EPL',
    },
    {
        date: '01.02',
        time: '20:00',
        first: 'ManchesterUnited',
        second: 'Fulham',
        tournament: 'EPL',
    },
    {
        date: '01.02',
        time: '20:00',
        first: 'NottinghamForest',
        second: 'CrystalPalace',
        tournament: 'EPL',
    },
    {
        date: '01.02',
        time: '20:00',
        first: 'Como',
        second: 'Atalanta',
        tournament: 'Seria A',
    },
    {
        date: '01.02',
        time: '20:00',
        first: 'Lyon',
        second: 'Lille',
        tournament: 'Ligue 1',
    },
    {
        date: '01.02',
        time: '22:30',
        first: 'Tottenham',
        second: 'ManchesterCity',
        tournament: 'EPL',
    },
    {
        date: '01.02',
        time: '22:30',
        first: 'BorussiaDortmund',
        second: 'Heidenheim',
        tournament: 'Bundesliga',
    },
    {
        date: '01.02',
        time: '23:00',
        first: 'Cremonese',
        second: 'Inter',
        tournament: 'Seria A',
    },
    {
        date: '02.02',
        time: '01:45',
        first: 'Parma',
        second: 'Juventus',
        tournament: 'Seria A',
    },
    {
        date: '02.02',
        time: '01:45',
        first: 'Strasbourg',
        second: 'PSG',
        tournament: 'Ligue 1',
    },
    {
        date: '03.02',
        time: '01:45',
        first: 'Udinese',
        second: 'Roma',
        tournament: 'Seria A',
    },
    {
        date: '04.02',
        time: '01:45',
        first: 'Bologna',
        second: 'Milan',
        tournament: 'Seria A',
    },
    // {
    //     date: '',
    //     time: '',
    //     first: ,
    //     second: ,
    //     tournament: ,
    // },
    // {
    //     date: '',
    //     time: '',
    //     first: ,
    //     second: ,
    //     tournament: ,
    // },
    // {
    //     date: '',
    //     time: '',
    //     first: ,
    //     second: ,
    //     tournament: ,
    // },
]
